[package]
name = "zero2prod"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
actix-web = "4.11.0"
reqwest = "0.12.20"
tokio = { version = "1.45.1", features = ["full"] }
